pipeline:
  name: Build harness-practice
  identifier: Build_harness_practice_1788787043683
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build-and-push-ghcr
                  identifier: buildandpushghcr
                  spec:
                    connectorRef: ghcrconnector
                    repo: ghcr.io/vipulmahajan1988/harness-practice
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: githubpoc
        repoName: harness-practice
        build: <+input>
