pipeline:
  name: Build harness-practice
  identifier: Build_harness_practice_1788787043683
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: install-and-test
                  identifier: installandtest
                  spec:
                    connectorRef: account.harnessImage
                    image: node:22-alpine
                    shell: Sh
                    command: |-
                      echo "Installing dependencies..."
                      npm install
                      echo "Running tests..."
                      npm test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: push-image
        identifier: pushimage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: push-to-github
                  identifier: pushtogithub
                  spec:
                    connectorRef: ghcrconnector
                    repo: ghcr.io/vipulmahajan1988/harness-practice
                    tags:
                      - latest
  properties:
    ci:
      codebase:
        connectorRef: githubpoc
        repoName: harness-practice
        build: <+input>
